plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.ivwitt.mayacalendar'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.ivwitt.mayacalendar'
        minSdk 23
        targetSdk 34
        versionCode 4
        versionName '1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
